### PR TITLE
Move messy attr compilation into method

### PR DESCRIPTION
**Pull request by gryphonmyers**
Addresses https://github.com/batiste/pug-vdom/issues/11

### CODE REVIEW

**Comment by gryphonmyers** [comment]
Initially this was going to introduce a runtime lib, but I immediately realized there was no reason my refactored code couldn't be executed at build time (which will make it less bloated and faster at runtime).

**Comment by batiste** [comment]
@gryphonmyers if that can be done at compile time this is a huge improvement!

Maybe it is a bit of nitpicking but isn't this function a pure function and not a method? Also I have to say I have a bit of an hard time to understand how this works or what it does. May a couple of simple mocha tests could help me understand?

**Comment by gryphonmyers** [comment]
Heh, well it is a member of the compiler prototype right now, which makes
it a method but you are probably right about it being a pure function so it
probably doesn't need to be one. I'll take another look at it tomorrow and
move it out of the prototype if it can stand on its own.

Sure I can write tests, also happy to explain with words

**Comment by gryphonmyers** [comment]
Added some tests. Also I was an idiot, this stuff totally has to happen in the runtime lib like I initially wrote it.

**Pull request merged**
