### PR TITLE
Load parsed scripts

### PR DESCRIPTION
**Pull request by gryphonmyers**
Adds support for script execution in nodes that have parsed HTML strings. 

Adds some tests covering this functionality.

Also fixes previously broken tests - my bad!

### CODE REVIEW

**Comment by batiste** [comment]
Is this something that makes any sense in the context of the server? I find this feature disturbing and dangerous...

**Comment by gryphonmyers** [comment]
Sure well, it does respect pug's built in syntax for escaped vs non-escaped
HTML (you have to opt in to this behavior by using flags that pug warns
against). The nature of runtime HTML parsing has an additional quirk you
wouldn't get in a pre-compiled context though: your HTML you add to the DOM
won't run scripts. This means if you have an HTML snippet loaded in at
runtime with, say, a Twitter embed in it (my exact use case) it won't run.
If you had used the same pug template in a compiled context, however, it
would.

Sure running scripts in parsed HTML is risky, but I think that should be up
to the template's author to use or not use the sanitization flags.
Otherwise this just seems broken.

If it would make you more comfortable, I could hide this functionality
behind an additional compile-time flag?

**Comment by batiste** [comment]
@gryphonmyers this is a feature that works in the original PUG? Could you point me to it?

**Comment by albb0920** [comment]
I think the feature is quite nice and makes sense.

In pug-vdom, this works:
```pug
if condition
  script
    | alert("ok")
```

But this doesn't:
```pug
if condition
  | <script>alert("ok")</script>
```

Both works in original pug.
This is a side effect of how `runtime.makeHtmlNode` is implemented.

In the first example, the script tag is created by virtual-dom via createElement, which will run the script.
In the second example, the script tag is created in `runtime.makeHtmlNode`, through assigning `innerHTML`, which doesn't run the script.

What this patch does, is replace all script created in innerHTML, and re-create it with createElement, to allow the script to run.

In both examples, there's nothing dangerous.
Things only gets scary when people use user input, which is also allowed in original pug with a big warning in the document.

**Pull request merged**
