### PR TITLE
Support specific rendering of textNodes

### PR DESCRIPTION
**Pull request by johnkazer**
See issue #51

### CODE REVIEW

**Comment by gryphonmyers** [comment]
Acknowledging that I see this and will try to get to it soon. Feel free to ping me if I'm not getting to it

**Comment by batiste** [comment]
Would it be possible to write a little test for this?

**Comment by batiste** [comment]
Actually, this change is so simple, maybe no extra test is necessary. I am merging.

**Comment by johnkazer** [comment]
Thanks very much. Very busy week so thanks for going ahead without the test.

**Comment by gryphonmyers** [comment]
> Thanks very much. Very busy week so thanks for going ahead without the test.

You need this published?

**Comment by johnkazer** [comment]
Not any time soon, whenever you feel a new version is useful

**Comment by johnkazer** [comment]
I'm currently using pug-vdom in [a simple "Utilities" demo](https://github.com/jorgebucaran/hyperawesome) for how to use Pug templates with the Hyperapp framework - uses a local copy of pug-vdom, not production or anything.

**Pull request merged**
